#ifndef RCCLIB_H
#define RCCLIB_H

#include <stdint.h>
#include "def.h"
#include "../reg.h"

typedef uint32_t RCC_CLK;
typedef uint32_t RCC_RST;
typedef uint32_t RCC_PCLK;


//
// RCC Clock Types
//
typedef enum {
    RCC_NONE_CLK,
    RCC_PCLK_CLK,
    RCC_HSE_CLK,
    RCC_HSI16_CLK,
    RCC_MSI_CLK,
    RCC_HSI48_CLK,
    RCC_PLL_CLK,
    RCC_LSE_CLK,
    RCC_LSI_CLK,
    RCC_SYSCLK_CLK,
    RCC_ADC_CLK,
    RCC_RTC_CLK
} RCC_CLOCK_TYPE;

//
// Get the RCC clock module number
//
#define     RCC_CLK_(R, C) ((R<<5)|C)
#define     RCC_RST_(R, C) ((R<<5)|C)
#define     _RCC_REG_OFF(X) (X >> 5)
#define     _RCC_BIT_POS(X) (X & 0x1F) 

//
// RCC Clock Modules Registers and Offsets
//
#define     RCC_CLK_TSC         RCC_CLK_(R_RCC_AHB1ENR_OFF, N_TSCEN)
#define     RCC_CLK_CRC         RCC_CLK_(R_RCC_AHB1ENR_OFF, N_CRCEN)
#define     RCC_CLK_FLASH       RCC_CLK_(R_RCC_AHB1ENR_OFF, N_FLASHEN)
#define     RCC_CLK_DMA2        RCC_CLK_(R_RCC_AHB1ENR_OFF, N_DMA2EN)
#define     RCC_CLK_DMA1        RCC_CLK_(R_RCC_AHB1ENR_OFF, N_DMA1EN)
#define     RCC_CLK_RNG         RCC_CLK_(R_RCC_AHB2ENR_OFF, N_RNGEN)
#define     RCC_CLK_AES         RCC_CLK_(R_RCC_AHB2ENR_OFF, N_AESEN)
#define     RCC_CLK_ADC         RCC_CLK_(R_RCC_AHB2ENR_OFF, N_ADCEN)
#define     RCC_CLK_GPIOH       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIOHEN)
#define     RCC_CLK_GPIOE       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIOEEN)
#define     RCC_CLK_GPIOD       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIODEN)
#define     RCC_CLK_GPIOC       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIOCEN)
#define     RCC_CLK_GPIOB       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIOBEN)
#define     RCC_CLK_GPIOA       RCC_CLK_(R_RCC_AHB2ENR_OFF, N_GPIOAEN)
#define     RCC_CLK_QSPI        RCC_CLK_(R_RCC_AHB3ENR_OFF, N_QSPIEN)
#define     RCC_CLK_LPTIM1      RCC_CLK_(R_RCC_APB1ENR1_OFF, N_LPTIM1EN)
#define     RCC_CLK_OPAMPEN     RCC_CLK_(R_RCC_APB1ENR1_OFF, N_OPAMPEN)
#define     RCC_CLK_DAC1        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_DAC1EN)
#define     RCC_CLK_PWR         RCC_CLK_(R_RCC_APB1ENR1_OFF, N_PWREN)
#define     RCC_CLK_USBFS       RCC_CLK_(R_RCC_APB1ENR1_OFF, N_USBFSEN)
#define     RCC_CLK_CAN1        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_CAN1EN)
#define     RCC_CLK_CRS         RCC_CLK_(R_RCC_APB1ENR1_OFF, N_CRSEN)
#define     RCC_CLK_I2C3        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_I2C3EN)
#define     RCC_CLK_I2C2        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_I2C2EN)
#define     RCC_CLK_I2C1        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_I2C1EN)
#define     RCC_CLK_UART4       RCC_CLK_(R_RCC_APB1ENR1_OFF, N_UART4EN)
#define     RCC_CLK_USART3      RCC_CLK_(R_RCC_APB1ENR1_OFF, N_USART3EN)
#define     RCC_CLK_USART2      RCC_CLK_(R_RCC_APB1ENR1_OFF, N_USART2EN)
#define     RCC_CLK_SPI3        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_SPI3EN)
#define     RCC_CLK_SPI2        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_SPI2EN)
#define     RCC_CLK_WWDG        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_WWDGEN)
#define     RCC_CLK_RTCAPB      RCC_CLK_(R_RCC_APB1ENR1_OFF, N_RTCAPBEN)
#define     RCC_CLK_LCD         RCC_CLK_(R_RCC_APB1ENR1_OFF, N_LCDEN)
#define     RCC_CLK_TIM7        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_TIM7EN)
#define     RCC_CLK_TIM6        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_TIM6EN)
#define     RCC_CLK_TIM3        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_TIM3EN)
#define     RCC_CLK_TIM2        RCC_CLK_(R_RCC_APB1ENR1_OFF, N_TIM2EN)
#define     RCC_CLK_LPTIM2      RCC_CLK_(R_RCC_APB1ENR2_OFF, N_LPTIM2EN)
#define     RCC_CLK_SWPMI1      RCC_CLK_(R_RCC_APB1ENR2_OFF, N_SWPMI1EN)
#define     RCC_CLK_I2C4        RCC_CLK_(R_RCC_APB1ENR2_OFF, N_I2C4EN)
#define     RCC_CLK_LPUART1     RCC_CLK_(R_RCC_APB1ENR2_OFF, N_LPUART1EN)
#define     RCC_CLK_DFSDM1      RCC_CLK_(R_RCC_APB2ENR_OFF, N_DFSDM1EN)
#define     RCC_CLK_SAI1        RCC_CLK_(R_RCC_APB2ENR_OFF, N_SAI1EN)
#define     RCC_CLK_TIM16       RCC_CLK_(R_RCC_APB2ENR_OFF, N_TIM16EN)   
#define     RCC_CLK_TIM15       RCC_CLK_(R_RCC_APB2ENR_OFF, N_TIM15EN)
#define     RCC_CLK_USART1      RCC_CLK_(R_RCC_APB2ENR_OFF, N_USART1EN)
#define     RCC_CLK_SPI1        RCC_CLK_(R_RCC_APB2ENR_OFF, N_SPI1EN)
#define     RCC_CLK_TIM1        RCC_CLK_(R_RCC_APB2ENR_OFF, N_TIM1EN)
#define     RCC_CLK_SDMMC1      RCC_CLK_(R_RCC_APB2ENR_OFF, N_SDMMC1EN)
#define     RCC_CLK_FW          RCC_CLK_(R_RCC_APB2ENR_OFF, N_FWEN)
#define     RCC_CLK_SYSCFG      RCC_CLK_(R_RCC_APB2ENR_OFF, N_SYSCFGEN)


//
// RCC Reset Modules Registers and Offsets
//
#define     RCC_RST_TSC         RCC_RST_(R_RCC_AHB1RSTR_OFF, N_TSCRST)
#define     RCC_RST_CRC         RCC_RST_(R_RCC_AHB1RSTR_OFF, N_CRCRST)
#define     RCC_RST_FLASH       RCC_RST_(R_RCC_AHB1RSTR_OFF, N_FLASHRST)
#define     RCC_RST_DMA2        RCC_RST_(R_RCC_AHB1RSTR_OFF, N_DMA2RST)
#define     RCC_RST_DMA1        RCC_RST_(R_RCC_AHB1RSTR_OFF, N_DMA1RST)
#define     RCC_RST_RNG         RCC_RST_(R_RCC_AHB2RSTR_OFF, N_RNGRST)
#define     RCC_RST_AES         RCC_RST_(R_RCC_AHB2RSTR_OFF, N_AESRST)
#define     RCC_RST_ADC         RCC_RST_(R_RCC_AHB2RSTR_OFF, N_ADCRST)
#define     RCC_RST_GPIOH       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIOHRST)
#define     RCC_RST_GPIOE       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIOERST)
#define     RCC_RST_GPIOD       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIODRST)
#define     RCC_RST_GPIOC       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIOCRST)
#define     RCC_RST_GPIOB       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIOBRST)
#define     RCC_RST_GPIOA       RCC_RST_(R_RCC_AHB2RSTR_OFF, N_GPIOARST)
#define     RCC_RST_QSPI        RCC_RST_(R_RCC_AHB3RSTR_OFF, N_QSPIRST)
#define     RCC_RST_LPTIM1      RCC_RST_(R_RCC_APB1RSTR1_OFF, N_LPTIM1RST)
#define     RCC_RST_OPAMP       RCC_RST_(R_RCC_APB1RSTR1_OFF, N_OPAMPRST)
#define     RCC_RST_DAC1        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_DAC1RST)
#define     RCC_RST_PWR         RCC_RST_(R_RCC_APB1RSTR1_OFF, N_PWRRST)
#define     RCC_RST_USBFS       RCC_RST_(R_RCC_APB1RSTR1_OFF, N_USBFSRST)
#define     RCC_RST_CAN1        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_CAN1RST)
#define     RCC_RST_CRS         RCC_RST_(R_RCC_APB1RSTR1_OFF, N_CRSRST)
#define     RCC_RST_I2C3        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_I2C3RST)
#define     RCC_RST_I2C2        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_I2C2RST)
#define     RCC_RST_I2C1        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_I2C1RST)
#define     RCC_RST_UART4       RCC_RST_(R_RCC_APB1RSTR1_OFF, N_UART4RST)
#define     RCC_RST_USART3      RCC_RST_(R_RCC_APB1RSTR1_OFF, N_USART3RST)
#define     RCC_RST_USART2      RCC_RST_(R_RCC_APB1RSTR1_OFF, N_USART2RST)
#define     RCC_RST_SPI3        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_SPI3RST)
#define     RCC_RST_SPI2        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_SPI2RST)
#define     RCC_RST_LCD         RCC_RST_(R_RCC_APB1RSTR1_OFF, N_LCDRST)
#define     RCC_RST_TIM7        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_TIM7RST)
#define     RCC_RST_TIM6        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_TIM6RST)
#define     RCC_RST_TIM3        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_TIM3RST)
#define     RCC_RST_TIM2        RCC_RST_(R_RCC_APB1RSTR1_OFF, N_TIM2RST)
#define     RCC_RST_LPTIM2      RCC_RST_(R_RCC_APB1RSTR2_OFF, N_LPTIM2RST)
#define     RCC_RST_SWPMI1      RCC_RST_(R_RCC_APB1RSTR2_OFF, N_SWPMI1RST)
#define     RCC_RST_I2C4        RCC_RST_(R_RCC_APB1RSTR2_OFF, N_I2C4RST)
#define     RCC_RST_LPUART1     RCC_RST_(R_RCC_APB1RSTR2_OFF, N_LPUART1RST)
#define     RCC_RST_DFSFM1      RCC_RST_(R_RCC_APB2RSTR_OFF, N_DFSDM1RST)
#define     RCC_RST_SAI1        RCC_RST_(R_RCC_APB2RSTR_OFF, N_SAI1RST)
#define     RCC_RST_TIM16       RCC_RST_(R_RCC_APB2RSTR_OFF, N_TIM16RST)
#define     RCC_RST_TIM15       RCC_RST_(R_RCC_APB2RSTR_OFF, N_TIM15RST)
#define     RCC_RST_USART1      RCC_RST_(R_RCC_APB2RSTR_OFF, N_USART1RST)
#define     RCC_RST_SPI1        RCC_RST_(R_RCC_APB2RSTR_OFF, N_SPI1RST)
#define     RCC_RST_TIM1        RCC_RST_(R_RCC_APB2RSTR_OFF, N_TIM1RST)
#define     RCC_RST_SDMMC1      RCC_RST_(R_RCC_APB2RSTR_OFF, N_SDMMC1RST)
#define     RCC_RST_SYSCFG      RCC_RST_(R_RCC_APB2RSTR_OFF, N_SYSCFGRST)


//
// Peripheral Clock MUX Definitions
//
/*
    Possible Clock Sources:
    BITS
    0-3     MUX 00 CLK source
    4-7     MUX 01 CLK source
    8-11    MUX 10 CLK source
    12-15   MUX 11 CLK source
    16-20   Position of Mux Bits in Register
    21      MUX USED
    22      AHB Prescaled
    23      APB1 Prescaled
    24      APB2 Prescaled
    25-31  Special for SAI1, USB, RNG, ADC, and UNUSED

*/
#define     RCC_CLK_MUX_USED        0x200000U
#define     RCC_CLK_AHB_PRESC       0x400000U
#define     RCC_CLK_APB1_PRESC      0x800000U
#define     RCC_CLK_APB2_PRESC      0x1000000U
#define     RCC_CLK_48MHZ           0x2000000U
#define     RCC_CLK_SYSCLK          0x4000000U
#define     RCC_CLK_CCIPR2          0x8000000U
#define     RCC_PCLK_(M0, M1, M2, M3, P) (M0|(M1<<4)|(M2<<8)|(M3<<12)|(P<<16))|RCC_CLK_MUX_USED
#define     _PCLK_MUX0(X)       (X & 0xF)
#define     _PCLK_MUX1(X)       ((X >> 4) & 0xF)
#define     _PCLK_MUX2(X)       ((X >> 8) & 0xF)
#define     _PCLK_MUX3(X)       ((X >> 12) & 0xF)
#define     _PCLK_BIT_OFF(X)    ((X >> 16) & 0x1F)

#define	    RCC_PCLK_TSC        RCC_CLK_AHB_PRESC         
#define	    RCC_PCLK_CRC        RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_FLASH      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_DMA2       RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_DMA1       RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_RNG        RCC_CLK_48MHZ
#define	    RCC_PCLK_AES        RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_ADC        RCC_CLK_SYSCLK // FIX
#define	    RCC_PCLK_GPIOH      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_GPIOE      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_GPIOD      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_GPIOC      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_GPIOB      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_GPIOA      RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_QSPI       RCC_CLK_AHB_PRESC
#define	    RCC_PCLK_LPTIM1     RCC_PCLK_(RCC_CLK_MUX_PCLK, RCC_LSI_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 18) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_OPAMPEN    RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_DAC1       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_PWR        RCC_CLK_SYSCLK
#define	    RCC_PCLK_USBFS      RCC_CLK_48MHZ
#define	    RCC_PCLK_CAN1       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_CRS        RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_I2C3       RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_NONE_CLK, 16) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_I2C2       RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_NONE_CLK, 14) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_I2C1       RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_NONE_CLK, 12) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_UART4      RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 6) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_USART3     RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 4) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_USART2     RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 2) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_SPI3       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_SPI2       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_WWDG       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_RTCAPB     RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC     
#define	    RCC_PCLK_LCD        RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_TIM7       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_TIM6       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_TIM3       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_TIM2       RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_LPTIM2     RCC_PCLK_(RCC_PCLK_CLK, RCC_LSI_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 20) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_SWPMI1     RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_NONE_CLK, RCC_NONE_CLK, 30) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_I2C4       RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_NONE_CLK, 0) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC | RCC_CLK_CCIPR2
#define	    RCC_PCLK_LPUART1    RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 10) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_DFSDM1     RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 0) | RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_SAI1       RCC_CLK_SYSCLK // FIX
#define	    RCC_PCLK_TIM16      RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_TIM15      RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_USART1     RCC_PCLK_(RCC_PCLK_CLK, RCC_SYSCLK_CLK, RCC_HSI16_CLK, RCC_LSE_CLK, 0) | RCC_CLK_AHB_PRESC | RCC_CLK_APB1_PRESC
#define	    RCC_PCLK_SPI1       RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_TIM1       RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_SDMMC1     RCC_CLK_48MHZ
#define	    RCC_PCLK_FW         RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC
#define	    RCC_PCLK_SYSCFG     RCC_CLK_AHB_PRESC | RCC_CLK_APB2_PRESC



/*
    Enables or disables a peripheral clock.

    @param  clk         Peripheral clock
    @param  clkState    On/off state

*/
void rccSetClock(RCC_CLK clk, RCC_CLK_STATE clkState);


/*
    Resets a peripheral, reseting all register values to defaults.

    @param  rst         Peripheral to Reset

*/
void rccReset(RCC_RST rst);

uint32_t rccGetClockFreq(RCC_CLOCK_TYPE clk);
uint32_t rccGetPerphClkFreq(RCC_PCLK pclk);

#endif